name: Second Workflow
on: workflow_dispatch

jobs:
  hello-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Hello second workflow
        run: echo "Hello second workflow"
  bye-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Bye second workflow
        run: echo "Bye second workflow" 
  
